---
abstract: 'Manipulate sets of IP addresses'
author:
  - 'Andy Armstrong <andy.armstrong@messagesystems.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CIDR-Set
provides:
  Net::CIDR::Set:
    file: lib/Net/CIDR/Set.pm
    version: 0.13
  Net::CIDR::Set::IPv4:
    file: lib/Net/CIDR/Set/IPv4.pm
    version: 0.13
  Net::CIDR::Set::IPv6:
    file: lib/Net/CIDR/Set/IPv6.pm
    version: 0.13
requires:
  Test::More: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-CIDR-Set
  license: http://dev.perl.org/licenses/
  repository: 'git://github.com/AndyA/Net--CIDR--Set.git (fetch)'
version: 0.13
